baseURL = 'https://jqliu-02.github.io/'
languageCode = 'zh-cn'
title = 'Jie Liu | GameDev - Agent - Leetcode'
theme = 'PaperMod'

pagination.pagerSize = 10
enableRobotsTXT = true

[taxonomies]
tag = "tags"
category = "categories"

[params]
author = "Jie Liu"
defaultTheme = "auto"

ShowReadingTime = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowToc = true

mainSections = ["posts", "projects"]

homeInfoParams.Title = "Hello"
homeInfoParams.Content = """
研一 CS Student

Game Client Development

Agent Learning

Leetcode Practice
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/JQLiu-02"

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 10

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 20

[[menu.main]]
name = "About"
url = "/about/"
weight = 30

[caches]
  [caches.images]
    dir = ':cacheDir/images'
