baseURL = 'https://jqliu-02.github.io/'
languageCode = 'zh-cn'
title = 'JQ Liu | GameDev - Agent - Leetcode'
theme = 'PaperMod'

pagination.pagerSize = 10
enableRobotsTXT = true

[taxonomies]
tag = "tags"
category = "categories"

[params]
author = "JQ Liu"
defaultTheme = "auto"

ShowReadingTime = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowToc = true

[params.profileMode]
enabled = true
title = "Jie Liu"
subtitle = "研一 | Software Engineering | Game Client - Agent - LeetCode"

[[params.profileMode.buttons]]
name = "Posts"
url = "/posts/"

[[params.profileMode.buttons]]
name = "Projects"
url = "/projects/"


[[params.profileMode.buttons]]
name = "About"
url = "/about/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/JQLiu-02"

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 10

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 20

[[menu.main]]
name = "About"
url = "/about/"
weight = 30

[caches]
  [caches.images]
    dir = ':cacheDir/images'
